# base image
FROM node:lts-alpine

# install simple http server for serving static content
RUN npm install -g http-server

# set working directory
WORKDIR /web_app

# install and cache app dependencies
COPY package*.json ./
RUN npm install


# copy project files and folders to the current working directory (i.e. 'web_app' folder)
COPY . .

# build app for production with minification
RUN npm run build

# Expose port for webserver
EXPOSE 8080
CMD [ "http-server", "dist" ]