# build stage
FROM node:lts-alpine as build-stage
WORKDIR /web_app
COPY package*.json ./
RUN npm install
COPY . .
RUN npm run build

# production stage
FROM nginx:stable-alpine as production-stage
COPY --from=build-stage /web_app/dist /usr/share/nginx/html

# Expose port for webserver
EXPOSE 80

CMD ["nginx", "-g", "daemon off;"]